
import java.util.Random;


public class DriverException extends Exception
{
    private int id;
    private int oldID;
    public DriverException (int id)
    {
        oldID=id;
        this.id=generateID();
    }
    public static int getNewID()
    {
        return id;
    }
    public int generateID ()
    {
        /*Random r = new Random ();
        int id = 3000000 + r.nextInt(999999);*/
        int id = (int) ((Math.random() * ((3999999 - 3000000)+1))+3000000);
        return id;
    }
    public String toString()
    {
        return "The Driver ID "+oldID+" was not valid and a new ID ( "+id+" ) is generated by admin and assigned to the Driver";
    }
    
}
