public class PolicyException extends Exception{
  public int userID;
  public int oldID;
  public int genID;
  public PolicyException (int id){
    oldID = id;
    this.userID = genID();
  }

  @Override
  public String toString() {
    return "The PolicyID was not valid and a new ID " + genID + ", is generated by admin and assigned for the Policy";
  }

  public int genID(){
    int max = 3999999;
    int min = 3000000;

      genID = (int)Math.floor(Math.random() * (max - min + 1) + min);
      //Do a check for id's that exist in the insuranceCompnay or in users?
    return genID;
  }
}
